Class {
	#name : #FamixJVMProfilerModel,
	#superclass : #MooseModel,
	#traits : 'FamixJVMProfilerTEntityCreator',
	#classTraits : 'FamixJVMProfilerTEntityCreator classTrait',
	#category : #'Famix-JavaProfiler-Entities-Model'
}

{ #category : #accessing }
FamixJVMProfilerModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits')
]

{ #category : #meta }
FamixJVMProfilerModel class >> annotation [
	<FMClass: #FamixJVMProfilerModel super: #MooseModel>
	<package: #'Famix-JavaProfiler-Entities'>
	<generated>
]
